<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyTitle>VoiceChatShared</AssemblyTitle>
		<Version>0.0.0</Version>
		<FileVersion>$(Version)</FileVersion>
		<OutputType>Library</OutputType>
		<TargetFrameworks>net35;net9.0</TargetFrameworks>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<AssemblyName>VoiceChatShared</AssemblyName>
		<ApplicationIcon>40bucks.ico</ApplicationIcon>
		<NeutralLanguage>en</NeutralLanguage>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<PathMap>$(MSBuildProjectDirectory)=./</PathMap>
		<Configurations>Release</Configurations>
		<!-- unsupported on net35 yet the new compiler complains about it-->
		<NoWarn>IDE0290,IDE0090,IDE0028</NoWarn>
	</PropertyGroup>

	<Target Name="ConvertToMdb" AfterTargets="Build" Condition=" '$(TargetFramework)' == 'net35' ">
		<PropertyGroup>
			<IsWindows>$([MSBuild]::IsOSPlatform('Windows'))</IsWindows>
			<MdbFixScriptPath>$(MSBuildProjectDirectory)\..\cleanupSymbolPaths.ps1</MdbFixScriptPath>
			<MdbPath>$(TargetPath).mdb</MdbPath>
			
			<Pdb2MdbToolPath Condition="'$(IsWindows)' == 'true'">$(PkgMono_pdb2mdb)\tools\pdb2mdb.exe</Pdb2MdbToolPath>
			<PowerShellBinary Condition="'$(IsWindows)' == 'true'">powershell.exe</PowerShellBinary>

			<PowerShellBinary Condition="'$(IsWindows)' != 'true'">pwsh</PowerShellBinary>
		</PropertyGroup>

		<Message Text="Converting Portable PDB to MDB..." Importance="high" Condition="'$(IsWindows)' != 'true'" />
		<Exec Command="ppdb2mdb &quot;$(TargetPath)&quot;" Condition="'$(IsWindows)' != 'true'" />

		<Error Text="The pdb2mdb NuGet package is missing." Condition="'$(IsWindows)' == 'true' AND !Exists('$(Pdb2MdbToolPath)')" />
		<Message Text="Converting PDB to MDB for $(TargetPath) using NuGet package..." Importance="high" Condition="'$(IsWindows)' == 'true'" />
		<Exec Command="&quot;$(Pdb2MdbToolPath)&quot; &quot;$(TargetPath)&quot;" Condition="'$(IsWindows)' == 'true'" />

		<Message Text="Applying byte-shift to remove './' prefix in $(MdbPath)..." Importance="high" />
		<Exec Command="$(PowerShellBinary) -ExecutionPolicy Bypass -File &quot;$(MdbFixScriptPath)&quot; -MdbPath &quot;$(MdbPath)&quot;" Condition="Exists('$(MdbPath)')" />
	</Target>

	<ItemGroup>
	  <PackageReference Include="Mono.pdb2mdb" Version="0.1.0.20130128" PrivateAssets="all" />
	</ItemGroup>
</Project>
