<Project Sdk="Microsoft.NET.Sdk">
	<!--
		YO!!
		
		if you don't have unity 2017.4.34f1 installed or it's in another path the build ****WILL FAIL****
		in that case create a file called Directory.Build.props alongside this file with these contents:
			
		<Project>
			<PropertyGroup>
				<UnityFolder>P:\ath\to\your\editor\install\</UnityFolder>
			</PropertyGroup>
		</Project>
			
		replace the path with the path to your unity editor installation and make sure to include the trailing backslash
		the specified folder should contain a folder called "Editor" and inside that a folder called "Data"
	-->
	
	<PropertyGroup>
		<AssemblyTitle>HexaModUnityEditor</AssemblyTitle>
		<Version>0.0.0</Version>
		<FileVersion>$(Version)</FileVersion>
		<OutputType>Library</OutputType>
		<TargetFramework>net35</TargetFramework>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<AssemblyName>HexaModUnityEditor</AssemblyName>
		<ApplicationIcon>40bucks.ico</ApplicationIcon>
		<NeutralLanguage>en</NeutralLanguage>
		<Product>HexaMod UnityEditor</Product>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<PathMap>$(MSBuildProjectDirectory)=./</PathMap>
		<Configurations>Release</Configurations>
		<NoWarn>IDE0290</NoWarn>
	</PropertyGroup>

	<Target Name="GenerateVersionInfo" BeforeTargets="CoreCompile">
		<PropertyGroup>
			<TempGitHashFile>$(IntermediateOutputPath)githash.tmp</TempGitHashFile>
		</PropertyGroup>

		<Exec Command="git describe --long --always --dirty &gt; &quot;$(TempGitHashFile)&quot;" />
		
		<ReadLinesFromFile File="$(TempGitHashFile)">
			<Output TaskParameter="Lines" ItemName="GitHashFromFile" />
		</ReadLinesFromFile>
		
		<PropertyGroup>
			<GitHash>@(GitHashFromFile)</GitHash>
			<GitHash Condition="'$(GitHash)' != ''">$(GitHash.Trim())</GitHash>
			<VersionInfoText>
// &lt;auto-generated&gt;
// This file is auto-generated by the build. Do not edit.
// &lt;/auto-generated&gt;
internal static class BuildInfo
{
	public const string Version = "$(Version)"%3B
	public const string GitHash = "$(GitHash)"%3B
	public const string AssemblyName = "$(AssemblyName)"%3B
	public const string AssemblyTitle = "$(AssemblyTitle)"%3B
}
			</VersionInfoText>
		</PropertyGroup>

		<Message Text="Generating BuildInfo.g.cs with Version $(Version)" Importance="high" />

		<WriteLinesToFile File="$(IntermediateOutputPath)BuildInfo.g.cs" Lines="$(VersionInfoText)" Overwrite="true" />

		<ItemGroup>
			<Compile Include="$(IntermediateOutputPath)BuildInfo.g.cs" />
		</ItemGroup>
	</Target>

	<Target Name="ConvertToMdb" AfterTargets="Build">
		<PropertyGroup>
			<IsWindows>$([MSBuild]::IsOSPlatform('Windows'))</IsWindows>
			<MdbFixScriptPath>$(MSBuildProjectDirectory)\..\cleanupSymbolPaths.ps1</MdbFixScriptPath>
			<MdbPath>$(TargetPath).mdb</MdbPath>
			
			<Pdb2MdbToolPath Condition="'$(IsWindows)' == 'true'">$(PkgMono_pdb2mdb)\tools\pdb2mdb.exe</Pdb2MdbToolPath>
			<PowerShellBinary Condition="'$(IsWindows)' == 'true'">powershell.exe</PowerShellBinary>

			<PowerShellBinary Condition="'$(IsWindows)' != 'true'">pwsh</PowerShellBinary>
		</PropertyGroup>

		<Message Text="Converting Portable PDB to MDB..." Importance="high" Condition="'$(IsWindows)' != 'true'" />
		<Exec Command="ppdb2mdb &quot;$(TargetPath)&quot;" Condition="'$(IsWindows)' != 'true'" />

		<Error Text="The pdb2mdb NuGet package is missing." Condition="'$(IsWindows)' == 'true' AND !Exists('$(Pdb2MdbToolPath)')" />
		<Message Text="Converting PDB to MDB for $(TargetPath) using NuGet package..." Importance="high" Condition="'$(IsWindows)' == 'true'" />
		<Exec Command="&quot;$(Pdb2MdbToolPath)&quot; &quot;$(TargetPath)&quot;" Condition="'$(IsWindows)' == 'true'" />

		<Message Text="Applying byte-shift to remove './' prefix in $(MdbPath)..." Importance="high" />
		<Exec Command="$(PowerShellBinary) -ExecutionPolicy Bypass -File &quot;$(MdbFixScriptPath)&quot; -MdbPath &quot;$(MdbPath)&quot;" Condition="Exists('$(MdbPath)')" />
	</Target>

	<ItemGroup>
		<ProjectReference Include="..\HexaMod\HexaMod.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<UnityFolder Condition=" '$(UnityFolder)' == '' ">C:\Program Files\Unity\Hub\Editor\2017.4.34f1\</UnityFolder>
	</PropertyGroup>

	<PropertyGroup>
		<UnityData Condition=" '$(UnityData)' == '' ">Editor\Data</UnityData>
	</PropertyGroup>

	<Target Name="CheckUnityPath" BeforeTargets="Build">
		<Error Text="The unity editor folder was not found at '$(UnityFolder)'. Please set the path correctly in Directory.Build.props as described in the comment in HexaModEditor.csproj" Condition="!Exists('$(UnityFolder)')" />
	</Target>

	<ItemGroup>
		<Reference Include="$(UnityFolder)\$(UnityData)\Managed\UnityEngine\*.dll" />
		<Reference Include="$(UnityFolder)\$(UnityData)\Managed\*.dll" Exclude="$(UnityFolder)\$(UnityData)\Managed\UnityEngine*" />
		<PackageReference Include="Mono.pdb2mdb" Version="0.1.0.20130128" PrivateAssets="all" />
	</ItemGroup>
</Project>